name: Frictionless Repository
description: Continious data validation
author: Frictionless Data
inputs:
  myInput:
    description: Input to use
    default: world
runs:
  using: docker
  image: Dockerfile
